version: '3'
services:
  database:
    image: postgres:15
    container_name: project-1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=project